server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/battlearena}
      database: ${MONGODB_DATABASE:battlearena}
